#!/usr/bin/env bash
#
# linkcheck.sh — verify that every repo-relative image reference in README.md
# actually exists in the repository. This guards the public GitHub profile page
# against broken-image regressions (a missing committed asset would otherwise
# show a broken image on the user's profile).
#
# Behaviour:
#   * raw.githubusercontent.com URLs pointing at the `main` branch are treated as
#     repo-relative paths and verified with `test -f` against the checked-out tree.
#   * raw.githubusercontent.com URLs pointing at other branches (output/projects)
#     are generated by workflows; they are verified with curl -I but a failure is
#     reported as a WARNING only (so transient network/rate-limit issues can't
#     break an otherwise-good PR).
#   * Plain relative paths (assets/..., projects/..., root *.svg) are verified with
#     `test -f` against the repo root.
#   * Any other URL (img.shields.io badges, streak-stats, etc.) is skipped.
#
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

README="README.md"
[ -f "$README" ] || { echo "ERROR: $README not found in $REPO_ROOT"; exit 1; }

echo "== linkcheck: verifying repo-relative image references in $README =="
echo "   repo root: $REPO_ROOT"

rc=0
warned=0

check_local() {
  # $1 = path relative to repo root
  if [ -f "$1" ]; then
    echo "OK    (local)   $1"
    return 0
  else
    echo "FAIL  (local)   $1  -> file not found in repo"
    rc=1
    return 1
  fi
}

# Collect every double-quoted token from the README that is a likely image ref.
# (deduped so a URL used in both <source srcset> and <img src> is not checked twice)
mapfile -t tokens < <(grep -oE '"[^"]+"' "$README" | sed 's/^"//; s/"$//' | sort -u)

for t in "${tokens[@]}"; do
  [ -z "$t" ] && continue
  case "$t" in
    https://raw.githubusercontent.com/*)
      rest="${t#https://raw.githubusercontent.com/}"
      owner="${rest%%/*}"; rest="${rest#*/}"
      repo="${rest%%/*}";  rest="${rest#*/}"
      branch="${rest%%/*}"; path="${rest#*/}"
      if [ "$branch" = "main" ]; then
        check_local "$path"
      else
        code=$(curl -s -o /dev/null -w '%{http_code}' -L --max-time 20 "$t" 2>/dev/null || echo "000")
        code="${code:0:3}"   # tolerate malformed/duplicated code output
        case "$code" in
          200|301|302)
            echo "OK    (remote/$branch) $path"
            ;;
          *)
            echo "WARN  (remote/$branch) $path -> HTTP $code (generated asset; not blocking)"
            warned=1
            ;;
        esac
      fi
      ;;
    http://*|https://*)
      # Any other absolute URL (shields.io badges, github actions badge,
      # streak-stats, etc.) is intentionally skipped.
      ;;
    *.svg|*.png|*.jpg|*.jpeg|*.gif)
      # Local relative path with no scheme (e.g. assets/foo.svg, projects/bar.svg).
      check_local "$t"
      ;;
    *)
      # Non-image / other token — intentionally skipped.
      ;;
  esac
done

echo "----------------------------------------"
if [ "$rc" -eq 0 ]; then
  echo "linkcheck: PASS (no broken repo-relative image links)"
  [ "$warned" -ne 0 ] && echo "linkcheck: note — $warned remote asset(s) issued a WARNING (non-blocking)"
  exit 0
else
  echo "linkcheck: FAIL — one or more repo-relative image links are broken"
  exit 1
fi
